#############################################################################
# Generated by PAGE version 4.0
# in conjunction with Tcl version 8.5
#    May. 23, 2013 09:41:36 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top34
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    set site_3_0 $base.fra35
    set site_4_0 $site_3_0.fra36
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 1x1+0+0; update
    wm maxsize $top 1009 570
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page.tcl"
    bindtags $top "$top Page.tcl all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top34 {base} {
    if {$base == ""} {
        set base .top34
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 765x463+43+54; update
    wm maxsize $top 1009 570
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    ttk::style configure Frame -background #d9d9d9
    ttk::style configure Frame -foreground #000000
    ttk::style configure Frame -font TkDefaultFont
    frame $top.fra35 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 395 \
        -highlightcolor black -width 525 
    vTcl:DefineAlias "$top.fra35" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra35
    label $site_3_0.lab34 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {CSV/log file:} 
    vTcl:DefineAlias "$site_3_0.lab34" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab35 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text /media/nonos/blablah/whatever/something.csv 
    vTcl:DefineAlias "$site_3_0.lab35" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab36 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {At row/frame:} 
    vTcl:DefineAlias "$site_3_0.lab36" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab37 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text 42 
    vTcl:DefineAlias "$site_3_0.lab37" "Label4" vTcl:WidgetProc "Toplevel1" 1
    canvas $site_3_0.can39 \
        -background white -borderwidth 2 -closeenough 1.0 -height 265 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 379 
    vTcl:DefineAlias "$site_3_0.can39" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text (*) 
    vTcl:DefineAlias "$site_3_0.lab40" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab38 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {GUI conf file:} 
    vTcl:DefineAlias "$site_3_0.lab38" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text /media/nonos/blablah/whatever/something.conf 
    vTcl:DefineAlias "$site_3_0.lab39" "Label6" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but34 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Save 
    vTcl:DefineAlias "$site_3_0.but34" "Button1" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra36 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.fra36" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra36
    button $site_4_0.but35 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -padx 1.5m -state active -text Render 
    vTcl:DefineAlias "$site_4_0.but35" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but36 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -padx 1.5m -text < 
    vTcl:DefineAlias "$site_4_0.but36" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but37 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -padx 1.5m -text > 
    vTcl:DefineAlias "$site_4_0.but37" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but38 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -state active -text Quit 
    vTcl:DefineAlias "$site_4_0.but38" "Button5" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but34 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -padx 1m -text MToolbar 
    vTcl:DefineAlias "$site_4_0.but34" "Button6" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab34 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text PNG: 
    vTcl:DefineAlias "$site_4_0.lab34" "Label8" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but39 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#ff0000} -highlightcolor black \
        -padx 1.5m -text DEL 
    vTcl:DefineAlias "$site_4_0.but39" "Button7" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_4_0.che34 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 0 -foreground {#000000} \
        -highlightcolor black -justify left -padx 0 -text cfc -variable che34 
    vTcl:DefineAlias "$site_4_0.che34" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.cpd35 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -padx 1m -text Reload 
    vTcl:DefineAlias "$site_4_0.cpd35" "Button8" vTcl:WidgetProc "Toplevel1" 1
    grid $site_4_0.but35 \
        -in $site_4_0 -column 7 -row 1 -columnspan 1 -rowspan 1 -sticky e 
    grid $site_4_0.but36 \
        -in $site_4_0 -column 3 -row 1 -columnspan 1 -rowspan 1 -sticky e 
    grid $site_4_0.but37 \
        -in $site_4_0 -column 4 -row 1 -columnspan 1 -rowspan 1 -sticky e 
    grid $site_4_0.but38 \
        -in $site_4_0 -column 9 -row 1 -columnspan 1 -rowspan 1 -sticky e 
    grid $site_4_0.but34 \
        -in $site_4_0 -column 2 -row 1 -columnspan 1 -rowspan 1 -sticky e 
    grid $site_4_0.lab34 \
        -in $site_4_0 -column 5 -row 1 -columnspan 1 -rowspan 1 -sticky e 
    grid $site_4_0.but39 \
        -in $site_4_0 -column 8 -row 1 -columnspan 1 -rowspan 1 -sticky e 
    grid $site_4_0.che34 \
        -in $site_4_0 -column 6 -row 1 -columnspan 1 -rowspan 1 -sticky e 
    grid $site_4_0.cpd35 \
        -in $site_4_0 -column 1 -row 1 -columnspan 1 -rowspan 1 -sticky e 
    text $site_3_0.tex34 \
        -background white -font TkTextFont -foreground black -height 18 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -wrap none 
    .top34.fra35.tex34 configure -font TkTextFont
    .top34.fra35.tex34 insert end text
    vTcl:DefineAlias "$site_3_0.tex34" "Text1" vTcl:WidgetProc "Toplevel1" 1
    scrollbar $site_3_0.scr42 \
        -activebackground {#f9f9f9} -background {#d9d9d9} \
        -highlightcolor black -orient horizontal -troughcolor {#c4c4c4} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.scr42" "Scrollbar8" vTcl:WidgetProc "Toplevel1" 1
    scrollbar $site_3_0.scr43 \
        -activebackground {#f9f9f9} -background {#d9d9d9} \
        -highlightcolor black -troughcolor {#c4c4c4} -width 10 
    vTcl:DefineAlias "$site_3_0.scr43" "Scrollbar9" vTcl:WidgetProc "Toplevel1" 1
    grid $site_3_0.lab34 \
        -in $site_3_0 -column 1 -row 1 -columnspan 2 -rowspan 1 -sticky e 
    grid $site_3_0.lab35 \
        -in $site_3_0 -column 3 -row 1 -columnspan 1 -rowspan 1 -sticky w 
    grid $site_3_0.lab36 \
        -in $site_3_0 -column 1 -row 2 -columnspan 2 -rowspan 1 -sticky e 
    grid $site_3_0.lab37 \
        -in $site_3_0 -column 3 -row 2 -columnspan 1 -rowspan 1 -sticky w 
    grid $site_3_0.can39 \
        -in $site_3_0 -column 1 -row 3 -columnspan 4 -rowspan 1 -sticky nesw 
    grid $site_3_0.lab40 \
        -in $site_3_0 -column 1 -row 4 -columnspan 1 -rowspan 1 -sticky w 
    grid $site_3_0.lab38 \
        -in $site_3_0 -column 2 -row 4 -columnspan 1 -rowspan 1 -sticky e 
    grid $site_3_0.lab39 \
        -in $site_3_0 -column 3 -row 4 -columnspan 1 -rowspan 1 -sticky w 
    grid $site_3_0.but34 \
        -in $site_3_0 -column 2 -row 5 -columnspan 1 -rowspan 1 -sticky w 
    grid $site_3_0.fra36 \
        -in $site_3_0 -column 3 -row 5 -columnspan 1 -rowspan 1 -sticky ew 
    grid columnconf $site_3_0.fra36 9 -weight 1
    grid $site_3_0.tex34 \
        -in $site_3_0 -column 1 -row 6 -columnspan 3 -rowspan 1 -sticky nesw 
    grid $site_3_0.scr42 \
        -in $site_3_0 -column 1 -row 7 -columnspan 3 -rowspan 1 -sticky ew 
    grid $site_3_0.scr43 \
        -in $site_3_0 -column 4 -row 6 -columnspan 1 -rowspan 1 -sticky ns 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra35 \
        -in $top -x 10 -y 10 -width 525 -height 395 -anchor nw \
        -bordermode ignore 
    grid columnconf $top.fra35 3 -weight 1
    grid rowconf $top.fra35 3 -weight 1
    grid rowconf $top.fra35 6 -weight 1

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top34

